import { fn } from 'storybook/test';
import type { Post } from '@dailydotdev/shared/src/graphql/posts';
import { PostType, UserVote } from '@dailydotdev/shared/src/graphql/posts';

const base: Partial<Post> = {
  bookmarked: false,
  read: false,
  upvoted: false,
  commented: false,
  userState: { vote: UserVote.None, flags: { feedbackDismiss: false } },
  type: PostType.Article,
  image:
    'https://media.daily.dev/image/upload/f_auto,q_auto/v1/posts/1f76bef532ec04b262c93b31de84abaa',
};

const source = (id: string, name: string): Post['source'] =>
  ({
    id,
    handle: id,
    name,
    permalink: `https://app.daily.dev/sources/${id}`,
    image: `https://media.daily.dev/image/upload/t_logo,f_auto/v1/logos/${id}`,
    type: 'machine',
    active: true,
    public: true,
  } as unknown as Post['source']);

/** Real-shaped article posts to fill a feed. */
export const feedPosts: Post[] = [
  {
    ...base,
    id: 'f-1',
    title: 'Why your CI is slow and how to fix it in an afternoon',
    permalink: 'https://api.daily.dev/r/f-1',
    commentsPermalink: 'https://app.daily.dev/posts/f-1',
    createdAt: '2026-08-26T08:00:00.000Z',
    readTime: 5,
    numUpvotes: 96,
    numComments: 12,
    tags: ['ci', 'devops'],
    source: source('devto', 'DEV Community'),
  },
  {
    ...base,
    id: 'f-2',
    title: 'Shipping HTTP/3 at the edge: what actually changed',
    permalink: 'https://api.daily.dev/r/f-2',
    commentsPermalink: 'https://app.daily.dev/posts/f-2',
    createdAt: '2026-08-25T15:00:00.000Z',
    readTime: 11,
    numUpvotes: 310,
    numComments: 40,
    tags: ['http3', 'networking'],
    source: source('cloudflare', 'Cloudflare Blog'),
  },
  {
    ...base,
    id: 'f-3',
    title: 'React Server Components, two years in',
    permalink: 'https://api.daily.dev/r/f-3',
    commentsPermalink: 'https://app.daily.dev/posts/f-3',
    createdAt: '2026-08-25T11:00:00.000Z',
    readTime: 9,
    numUpvotes: 154,
    numComments: 27,
    tags: ['react', 'webdev'],
    source: source('vercel', 'Vercel'),
  },
  {
    ...base,
    id: 'f-4',
    title: 'Postgres 18: the features worth upgrading for',
    permalink: 'https://api.daily.dev/r/f-4',
    commentsPermalink: 'https://app.daily.dev/posts/f-4',
    createdAt: '2026-08-24T10:00:00.000Z',
    readTime: 7,
    numUpvotes: 201,
    numComments: 19,
    tags: ['postgres', 'database'],
    source: source('supabase', 'Supabase'),
  },
  {
    ...base,
    id: 'f-5',
    title: 'A field guide to flaky tests',
    permalink: 'https://api.daily.dev/r/f-5',
    commentsPermalink: 'https://app.daily.dev/posts/f-5',
    createdAt: '2026-08-23T10:00:00.000Z',
    readTime: 6,
    numUpvotes: 88,
    numComments: 9,
    tags: ['testing'],
    source: source('devto', 'DEV Community'),
  },
  {
    ...base,
    id: 'f-6',
    title: 'Rust in the Linux kernel: a year of maintainer notes',
    permalink: 'https://api.daily.dev/r/f-6',
    commentsPermalink: 'https://app.daily.dev/posts/f-6',
    createdAt: '2026-08-22T10:00:00.000Z',
    readTime: 12,
    numUpvotes: 412,
    numComments: 58,
    tags: ['rust', 'linux'],
    source: source('lwn', 'LWN.net'),
  },
  {
    ...base,
    id: 'f-7',
    title: 'Designing idempotent webhooks that survive retries',
    permalink: 'https://api.daily.dev/r/f-7',
    commentsPermalink: 'https://app.daily.dev/posts/f-7',
    createdAt: '2026-08-21T10:00:00.000Z',
    readTime: 8,
    numUpvotes: 133,
    numComments: 14,
    tags: ['api', 'backend'],
    source: source('stripe', 'Stripe Engineering'),
  },
  {
    ...base,
    id: 'f-8',
    title: 'The case against microservices for teams under 20',
    permalink: 'https://api.daily.dev/r/f-8',
    commentsPermalink: 'https://app.daily.dev/posts/f-8',
    createdAt: '2026-08-20T10:00:00.000Z',
    readTime: 6,
    numUpvotes: 267,
    numComments: 71,
    tags: ['architecture'],
    source: source('devto', 'DEV Community'),
  },
] as Post[];

export const cardHandlers = {
  onPostClick: fn(),
  onPostAuxClick: fn(),
  onUpvoteClick: fn(),
  onDownvoteClick: fn(),
  onCommentClick: fn(),
  onBookmarkClick: fn(),
  onCopyLinkClick: fn(),
  onShare: fn(),
  onReadArticleClick: fn(),
};
