const accentColors = {
  burger: {
    subtlest: 'var(--theme-accent-burger-subtlest)',
    subtler: 'var(--theme-accent-burger-subtler)',
    subtle: 'var(--theme-accent-burger-subtle)',
    default: 'var(--theme-accent-burger-default)',
    bolder: 'var(--theme-accent-burger-bolder)',
  },
  blueCheese: {
    subtlest: 'var(--theme-accent-blueCheese-subtlest)',
    subtler: 'var(--theme-accent-blueCheese-subtler)',
    subtle: 'var(--theme-accent-blueCheese-subtle)',
    default: 'var(--theme-accent-blueCheese-default)',
    bolder: 'var(--theme-accent-blueCheese-bolder)',
  },
  avocado: {
    subtlest: 'var(--theme-accent-avocado-subtlest)',
    subtler: 'var(--theme-accent-avocado-subtler)',
    subtle: 'var(--theme-accent-avocado-subtle)',
    default: 'var(--theme-accent-avocado-default)',
    bolder: 'var(--theme-accent-avocado-bolder)',
  },
  cheese: {
    subtlest: 'var(--theme-accent-cheese-subtlest)',
    subtler: 'var(--theme-accent-cheese-subtler)',
    subtle: 'var(--theme-accent-cheese-subtle)',
    default: 'var(--theme-accent-cheese-default)',
    bolder: 'var(--theme-accent-cheese-bolder)',
  },
  salt: {
    baseline: 'var(--theme-accent-salt-baseline)',
    subtlest: 'var(--theme-accent-salt-subtlest)',
    subtler: 'var(--theme-accent-salt-subtler)',
    subtle: 'var(--theme-accent-salt-subtle)',
    default: 'var(--theme-accent-salt-default)',
    bolder: 'var(--theme-accent-salt-bolder)',
  },
  onion: {
    subtlest: 'var(--theme-accent-onion-subtlest)',
    subtler: 'var(--theme-accent-onion-subtler)',
    subtle: 'var(--theme-accent-onion-subtle)',
    default: 'var(--theme-accent-onion-default)',
    bolder: 'var(--theme-accent-onion-bolder)',
  },
  water: {
    subtlest: 'var(--theme-accent-water-subtlest)',
    subtler: 'var(--theme-accent-water-subtler)',
    subtle: 'var(--theme-accent-water-subtle)',
    default: 'var(--theme-accent-water-default)',
    bolder: 'var(--theme-accent-water-bolder)',
  },
  pepper: {
    baseline: 'var(--theme-accent-pepper-baseline)',
    subtlest: 'var(--theme-accent-pepper-subtlest)',
    subtler: 'var(--theme-accent-pepper-subtler)',
    subtle: 'var(--theme-accent-pepper-subtle)',
    default: 'var(--theme-accent-pepper-default)',
    bolder: 'var(--theme-accent-pepper-bolder)',
  },
  lettuce: {
    subtlest: 'var(--theme-accent-lettuce-subtlest)',
    subtler: 'var(--theme-accent-lettuce-subtler)',
    subtle: 'var(--theme-accent-lettuce-subtle)',
    default: 'var(--theme-accent-lettuce-default)',
    bolder: 'var(--theme-accent-lettuce-bolder)',
  },
  bun: {
    subtlest: 'var(--theme-accent-bun-subtlest)',
    subtler: 'var(--theme-accent-bun-subtler)',
    subtle: 'var(--theme-accent-bun-subtle)',
    default: 'var(--theme-accent-bun-default)',
    bolder: 'var(--theme-accent-bun-bolder)',
  },
  ketchup: {
    subtlest: 'var(--theme-accent-ketchup-subtlest)',
    subtler: 'var(--theme-accent-ketchup-subtler)',
    subtle: 'var(--theme-accent-ketchup-subtle)',
    default: 'var(--theme-accent-ketchup-default)',
    bolder: 'var(--theme-accent-ketchup-bolder)',
  },
  cabbage: {
    subtlest: 'var(--theme-accent-cabbage-subtlest)',
    subtler: 'var(--theme-accent-cabbage-subtler)',
    subtle: 'var(--theme-accent-cabbage-subtle)',
    default: 'var(--theme-accent-cabbage-default)',
    bolder: 'var(--theme-accent-cabbage-bolder)',
  },
  bacon: {
    subtlest: 'var(--theme-accent-bacon-subtlest)',
    subtler: 'var(--theme-accent-bacon-subtler)',
    subtle: 'var(--theme-accent-bacon-subtle)',
    default: 'var(--theme-accent-bacon-default)',
    bolder: 'var(--theme-accent-bacon-bolder)',
  },
};

export default accentColors;
