version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: next
    versions:
    - "> 10.0.5, < 10.1"
  - dependency-name: postcss
    versions:
    - 8.2.12
  - dependency-name: eslint-plugin-testing-library
    versions:
    - 4.0.0
    - 4.0.1
    - 4.1.0
    - 4.1.1
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.1.2
  - dependency-name: react-query
    versions:
    - 3.13.2
    - 3.13.6
    - 3.13.7
    - 3.8.1
    - 3.8.3
  - dependency-name: next-pwa
    versions:
    - 5.0.6
    - 5.1.4
    - 5.2.1
    - 5.2.3
  - dependency-name: preact-render-to-string
    versions:
    - 5.1.19
  - dependency-name: next
    versions:
    - 10.1.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.22
  - dependency-name: next-seo
    versions:
    - 4.23.0
  - dependency-name: "@emotion/jest"
    versions:
    - 11.2.1
  - dependency-name: swr
    versions:
    - 0.5.4
  - dependency-name: "@tailwindcss/jit"
    versions:
    - 0.1.7
  - dependency-name: preact
    versions:
    - 10.5.13
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.15.2
    - 4.17.0
    - 4.18.0
  - dependency-name: "@next/bundle-analyzer"
    versions:
    - 10.0.8
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.32
  - dependency-name: vercel
    versions:
    - 21.3.0
    - 21.3.1
    - 21.3.2
    - 21.3.3
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
    - 4.16.1
    - 4.17.0
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
  - dependency-name: stylelint
    versions:
    - 13.11.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: nock
    versions:
    - 13.0.7
