# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5002
    onOpen: open-browser
  - port: 4000
    onOpen: ignore
  - port: 5000
    onOpen: ignore
  - port: 6379
    onOpen: ignore
  - port: 5432
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: docker-compose
    init: docker-compose pull
    command: docker-compose up
  - name: seed
    before: |
      sudo apt-get update
      sudo apt-get install -y netcat
    init: |
      sleep 60
      ./wait-for.sh localhost:5000
    command: |
      docker exec apps-daily-api-1 node ./node_modules/typeorm/cli.js migration:run -d src/data-source.js
      docker exec apps-daily-api-1 node bin/import.js
  - name: webapp
    env:
      NEXT_PUBLIC_API_URL: http://localhost:5000
      NEXT_PUBLIC_SUBS_URL: ws://localhost:5000/graphql
      NEXT_PUBLIC_DOMAIN: localhost
      NEXT_PUBLIC_WEBAPP_URL: /
      NEXT_PUBLIC_AUTH_URL: http://localhost
      NEXT_PUBLIC_HEIMDALL_URL: http://localhost
    before: |
      nvm install
      nvm use
    init: |
      npm i -g pnpm@8.15.7
      pnpm install
    command: |
      cd packages/webapp
      npm run dev
