# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5002
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: docker-compose
    init: docker-compose pull
    command: docker-compose up
  - name: webapp
    before: |
      nvm install
      nvm use
    init: |
      npm i -g lerna
      lerna bootstrap
    command: |
      cd packages/webapp
      npm run start
