import type {
  GivebackAction,
  GivebackCampaign,
  GivebackCause,
  GivebackCommunityEvent,
  GivebackLevel,
  GivebackSponsor,
  GivebackUserAction,
  GivebackUserProfile,
} from './types';
import {
  GivebackActionCategory,
  GivebackActionPersona,
  GivebackActionPlatform,
  GivebackActionValidationType,
  GivebackCampaignStatus,
  GivebackCauseStatus,
  GivebackRewardStatus,
  GivebackRewardType,
  GivebackSponsorType,
  GivebackUserActionStatus,
} from './types';

// Phase 1 mock data. This is the single source of truth the baseline page renders
// from, and the dev review toggle drives it. Replaced by live queries in a later phase.

export const GIVEBACK_CURRENCY = 'USD';

export const givebackCauses: GivebackCause[] = [
  {
    id: 'cause-code-org',
    name: 'Code.org',
    description:
      'Expands access to computer science education for students and teachers.',
    url: 'https://code.org',
    category: 'Education',
    status: GivebackCauseStatus.Active,
    sortOrder: 1,
  },
  {
    id: 'cause-ef',
    name: 'Electronic Frontier Foundation',
    description:
      'Defends digital privacy, free expression, and user rights online.',
    url: 'https://eff.org',
    category: 'Digital rights',
    status: GivebackCauseStatus.Active,
    sortOrder: 2,
  },
  {
    id: 'cause-girls-who-code',
    name: 'Girls Who Code',
    description:
      'Works to close the gender gap in tech through education and community.',
    url: 'https://girlswhocode.com',
    category: 'Education',
    status: GivebackCauseStatus.Active,
    sortOrder: 3,
  },
  {
    id: 'cause-internet-archive',
    name: 'Internet Archive',
    description:
      'Keeps knowledge, web history, and digital culture accessible to everyone.',
    url: 'https://archive.org',
    category: 'Open web',
    status: GivebackCauseStatus.Active,
    sortOrder: 4,
  },
];

export const givebackCommunityEvents: GivebackCommunityEvent[] = [
  {
    id: 'event-1',
    actorLabel: 'A community member',
    actionLabel: 'shared the Giveback launch post',
    amount: 10,
    currency: GIVEBACK_CURRENCY,
    causeName: 'Code.org',
    createdAt: '2026-06-01T10:30:00.000Z',
    isAnonymous: true,
  },
  {
    id: 'event-2',
    actorLabel: 'A creator',
    actionLabel: 'submitted a daily.dev workflow video',
    amount: 50,
    currency: GIVEBACK_CURRENCY,
    causeName: 'Girls Who Code',
    createdAt: '2026-06-01T11:15:00.000Z',
    isAnonymous: true,
  },
  {
    id: 'event-3',
    actorLabel: 'A power user',
    actionLabel: 'invited a developer friend',
    amount: 15,
    currency: GIVEBACK_CURRENCY,
    causeName: 'Electronic Frontier Foundation',
    createdAt: '2026-06-01T12:20:00.000Z',
    isAnonymous: true,
  },
  {
    id: 'event-4',
    actorLabel: 'A Squad member',
    actionLabel: 'posted a developer tip',
    amount: 15,
    currency: GIVEBACK_CURRENCY,
    causeName: 'Internet Archive',
    createdAt: '2026-06-01T13:45:00.000Z',
    isAnonymous: true,
  },
  {
    id: 'event-5',
    actorLabel: 'Someone from the community',
    actionLabel: 'left optional app feedback for love',
    currency: GIVEBACK_CURRENCY,
    createdAt: '2026-06-01T15:00:00.000Z',
    isAnonymous: true,
  },
];

export const givebackActions: GivebackAction[] = [
  {
    id: 'share-launch-post',
    title: 'Share the Giveback launch post',
    description:
      'Post the official Giveback announcement with your own note about why it matters.',
    category: GivebackActionCategory.SocialMedia,
    platform: GivebackActionPlatform.X,
    personaTags: [
      GivebackActionPersona.Creator,
      GivebackActionPersona.PowerUser,
      GivebackActionPersona.CommunityMember,
    ],
    donationAmount: 10,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.Manual,
    requiresLink: true,
    requiresImage: false,
    requiresNote: true,
    isRewarded: true,
    donationEligible: true,
    isComplianceSensitive: false,
    isLoveAction: false,
    instructions: 'Share the campaign and submit the public post URL.',
  },
  {
    id: 'record-demo-video',
    title: 'Record a short daily.dev workflow video',
    description:
      'Show how daily.dev helps you discover, save, or discuss developer content.',
    category: GivebackActionCategory.CreatorContent,
    platform: GivebackActionPlatform.YouTube,
    personaTags: [
      GivebackActionPersona.Creator,
      GivebackActionPersona.PowerUser,
      GivebackActionPersona.SeniorDeveloper,
    ],
    donationAmount: 50,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.Manual,
    requiresLink: true,
    requiresImage: false,
    requiresNote: true,
    isRewarded: true,
    donationEligible: true,
    isComplianceSensitive: false,
    isLoveAction: false,
    instructions: 'Submit a public link to the video after posting it.',
  },
  {
    id: 'invite-dev-friend',
    title: 'Invite a developer friend',
    description:
      'Bring another developer into the community through an official invite flow.',
    category: GivebackActionCategory.Referrals,
    platform: GivebackActionPlatform.DailyDev,
    personaTags: [
      GivebackActionPersona.CommunityMember,
      GivebackActionPersona.PowerUser,
      GivebackActionPersona.TeamLead,
    ],
    donationAmount: 15,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.Automatic,
    requiresLink: false,
    requiresImage: false,
    requiresNote: false,
    isRewarded: true,
    donationEligible: true,
    isComplianceSensitive: false,
    isLoveAction: false,
    instructions:
      'Use your invite link. We validate accepted invites automatically.',
  },
  {
    id: 'refer-team',
    title: 'Refer a dev team',
    description:
      'Introduce daily.dev to a team that could benefit from shared discovery.',
    category: GivebackActionCategory.Referrals,
    platform: GivebackActionPlatform.LinkedIn,
    personaTags: [
      GivebackActionPersona.TeamLead,
      GivebackActionPersona.SeniorDeveloper,
      GivebackActionPersona.DailyPlusSubscriber,
    ],
    donationAmount: 40,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.Hybrid,
    requiresLink: false,
    requiresImage: false,
    requiresNote: true,
    isRewarded: true,
    donationEligible: true,
    isComplianceSensitive: false,
    isLoveAction: false,
    instructions:
      'Tell us who you introduced and we will validate the referral.',
  },
  {
    id: 'submit-product-feedback',
    title: 'Send thoughtful product feedback',
    description:
      'Share one product insight that would help make daily.dev better for developers.',
    category: GivebackActionCategory.ProductFeedback,
    platform: GivebackActionPlatform.DailyDev,
    personaTags: [
      GivebackActionPersona.PowerUser,
      GivebackActionPersona.SeniorDeveloper,
      GivebackActionPersona.Student,
    ],
    donationAmount: 10,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.Manual,
    requiresLink: false,
    requiresImage: false,
    requiresNote: true,
    isRewarded: true,
    donationEligible: true,
    isComplianceSensitive: false,
    isLoveAction: false,
  },
  {
    id: 'join-user-interview',
    title: 'Join a 20-minute user interview',
    description:
      'Talk to the team about your daily.dev habits, blockers, and wishlist.',
    category: GivebackActionCategory.ProductFeedback,
    platform: GivebackActionPlatform.DailyDev,
    personaTags: [
      GivebackActionPersona.PowerUser,
      GivebackActionPersona.SeniorDeveloper,
      GivebackActionPersona.TeamLead,
    ],
    donationAmount: 25,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.Manual,
    requiresLink: false,
    requiresImage: false,
    requiresNote: false,
    isRewarded: true,
    donationEligible: true,
    isComplianceSensitive: false,
    isLoveAction: false,
  },
  {
    id: 'post-community-tip',
    title: 'Post a developer tip in your community',
    description:
      'Share a practical daily.dev tip in a developer group, forum, or community space.',
    category: GivebackActionCategory.CommunityPosts,
    platform: GivebackActionPlatform.Reddit,
    personaTags: [
      GivebackActionPersona.CommunityMember,
      GivebackActionPersona.OpenSourceContributor,
      GivebackActionPersona.Student,
    ],
    donationAmount: 15,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.Manual,
    requiresLink: true,
    requiresImage: false,
    requiresNote: true,
    isRewarded: true,
    donationEligible: true,
    isComplianceSensitive: false,
    isLoveAction: false,
  },
  {
    id: 'write-blog-post',
    title: 'Write a blog post about your daily.dev setup',
    description:
      'Explain how you use daily.dev to stay current, organize reading, or follow topics.',
    category: GivebackActionCategory.CreatorContent,
    platform: GivebackActionPlatform.Hashnode,
    personaTags: [
      GivebackActionPersona.Creator,
      GivebackActionPersona.SeniorDeveloper,
      GivebackActionPersona.OpenSourceContributor,
    ],
    donationAmount: 50,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.Manual,
    requiresLink: true,
    requiresImage: false,
    requiresNote: false,
    isRewarded: true,
    donationEligible: true,
    isComplianceSensitive: false,
    isLoveAction: false,
  },
  {
    id: 'create-open-source-note',
    title: 'Mention daily.dev in an open-source resource list',
    description:
      'Add a relevant daily.dev recommendation to a public learning or tooling resource.',
    category: GivebackActionCategory.CommunityPosts,
    platform: GivebackActionPlatform.GitHub,
    personaTags: [
      GivebackActionPersona.OpenSourceContributor,
      GivebackActionPersona.Creator,
      GivebackActionPersona.Student,
    ],
    donationAmount: 25,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.Manual,
    requiresLink: true,
    requiresImage: false,
    requiresNote: true,
    isRewarded: true,
    donationEligible: true,
    isComplianceSensitive: false,
    isLoveAction: false,
  },
  {
    id: 'share-squad-story',
    title: 'Share a Squad success story',
    description:
      'Tell the community how a Squad helped you learn, collaborate, or discover content.',
    category: GivebackActionCategory.SocialMedia,
    platform: GivebackActionPlatform.X,
    personaTags: [
      GivebackActionPersona.CommunityMember,
      GivebackActionPersona.TeamLead,
      GivebackActionPersona.PowerUser,
    ],
    donationAmount: 20,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.Manual,
    requiresLink: true,
    requiresImage: true,
    requiresNote: true,
    isRewarded: true,
    donationEligible: true,
    isComplianceSensitive: false,
    isLoveAction: false,
  },
  {
    id: 'complete-onboarding-quiz',
    title: 'Complete the Giveback onboarding quiz',
    description:
      'Help us understand which actions and causes feel most relevant to you.',
    category: GivebackActionCategory.ProductFeedback,
    platform: GivebackActionPlatform.DailyDev,
    personaTags: [
      GivebackActionPersona.Student,
      GivebackActionPersona.CommunityMember,
      GivebackActionPersona.DailyPlusSubscriber,
    ],
    donationAmount: 5,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.Automatic,
    requiresLink: false,
    requiresImage: false,
    requiresNote: false,
    isRewarded: true,
    donationEligible: true,
    isComplianceSensitive: false,
    isLoveAction: false,
  },
  {
    id: 'honest-app-store-review',
    title: 'Leave an honest mobile app review',
    description:
      'If daily.dev has helped you, consider sharing an honest review. No rewards attached.',
    category: GivebackActionCategory.CommunityLove,
    platform: GivebackActionPlatform.AppStore,
    personaTags: [
      GivebackActionPersona.CommunityMember,
      GivebackActionPersona.PowerUser,
      GivebackActionPersona.DailyPlusSubscriber,
    ],
    donationAmount: 0,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.None,
    requiresLink: false,
    requiresImage: false,
    requiresNote: false,
    isRewarded: false,
    donationEligible: false,
    isComplianceSensitive: true,
    isLoveAction: true,
    instructions:
      'Reviews are voluntary and never unlock donation value, rewards, or product access.',
  },
  {
    id: 'chrome-store-love',
    title: 'Share honest Chrome Web Store feedback',
    description:
      'Optional feedback for people who already use the extension. No incentives or donation value.',
    category: GivebackActionCategory.CommunityLove,
    platform: GivebackActionPlatform.ChromeWebStore,
    personaTags: [
      GivebackActionPersona.PowerUser,
      GivebackActionPersona.CommunityMember,
      GivebackActionPersona.SeniorDeveloper,
    ],
    donationAmount: 0,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.None,
    requiresLink: false,
    requiresImage: false,
    requiresNote: false,
    isRewarded: false,
    donationEligible: false,
    isComplianceSensitive: true,
    isLoveAction: true,
  },
  {
    id: 'mentor-student',
    title: 'Help a student set up daily.dev',
    description:
      'Walk a student or junior developer through topic follows, bookmarks, and Squads.',
    category: GivebackActionCategory.CommunityPosts,
    platform: GivebackActionPlatform.DailyDev,
    personaTags: [
      GivebackActionPersona.Student,
      GivebackActionPersona.SeniorDeveloper,
      GivebackActionPersona.CommunityMember,
    ],
    donationAmount: 20,
    currency: GIVEBACK_CURRENCY,
    validationType: GivebackActionValidationType.Manual,
    requiresLink: false,
    requiresImage: false,
    requiresNote: true,
    isRewarded: true,
    donationEligible: true,
    isComplianceSensitive: false,
    isLoveAction: false,
  },
];

export const givebackUserActions: GivebackUserAction[] = [
  {
    actionId: 'share-launch-post',
    status: GivebackUserActionStatus.CountedTowardGoal,
    unlockedDonationAmount: 10,
    pendingDonationAmount: 0,
    approvedDonationAmount: 10,
    rejectedDonationAmount: 0,
    submittedAt: '2026-05-28T10:00:00.000Z',
    reviewedAt: '2026-05-28T13:00:00.000Z',
  },
  {
    actionId: 'record-demo-video',
    status: GivebackUserActionStatus.PendingReview,
    unlockedDonationAmount: 50,
    pendingDonationAmount: 50,
    approvedDonationAmount: 0,
    rejectedDonationAmount: 0,
    submittedAt: '2026-05-30T14:00:00.000Z',
  },
  {
    actionId: 'invite-dev-friend',
    status: GivebackUserActionStatus.Approved,
    unlockedDonationAmount: 15,
    pendingDonationAmount: 0,
    approvedDonationAmount: 15,
    rejectedDonationAmount: 0,
    submittedAt: '2026-05-29T09:00:00.000Z',
    reviewedAt: '2026-05-29T09:05:00.000Z',
  },
  {
    actionId: 'refer-team',
    status: GivebackUserActionStatus.Started,
    unlockedDonationAmount: 0,
    pendingDonationAmount: 0,
    approvedDonationAmount: 0,
    rejectedDonationAmount: 0,
  },
  {
    actionId: 'submit-product-feedback',
    status: GivebackUserActionStatus.NeedsMoreInfo,
    unlockedDonationAmount: 10,
    pendingDonationAmount: 0,
    approvedDonationAmount: 0,
    rejectedDonationAmount: 0,
    submittedAt: '2026-05-27T12:00:00.000Z',
    needsMoreInfoReason: 'Add one concrete example so we can validate it.',
  },
  {
    actionId: 'join-user-interview',
    status: GivebackUserActionStatus.Expired,
    unlockedDonationAmount: 0,
    pendingDonationAmount: 0,
    approvedDonationAmount: 0,
    rejectedDonationAmount: 0,
  },
  {
    actionId: 'post-community-tip',
    status: GivebackUserActionStatus.Rejected,
    unlockedDonationAmount: 15,
    pendingDonationAmount: 0,
    approvedDonationAmount: 0,
    rejectedDonationAmount: 15,
    submittedAt: '2026-05-26T16:00:00.000Z',
    reviewedAt: '2026-05-27T09:00:00.000Z',
    rejectionReason: 'The post was not publicly accessible.',
  },
  {
    actionId: 'share-squad-story',
    status: GivebackUserActionStatus.Submitted,
    unlockedDonationAmount: 20,
    pendingDonationAmount: 20,
    approvedDonationAmount: 0,
    rejectedDonationAmount: 0,
    submittedAt: '2026-06-01T08:30:00.000Z',
  },
  {
    actionId: 'complete-onboarding-quiz',
    status: GivebackUserActionStatus.AutoValidating,
    unlockedDonationAmount: 5,
    pendingDonationAmount: 5,
    approvedDonationAmount: 0,
    rejectedDonationAmount: 0,
    submittedAt: '2026-06-01T11:00:00.000Z',
  },
];

// A long, dynamic ladder (the journey UI only ever shows a window of it). Each
// blueprint becomes a level + reward; the welcome gift at level 1 is free just
// for showing up.
interface LevelBlueprint {
  name: string;
  required: number;
  reward: {
    type: GivebackRewardType;
    title: string;
    description?: string;
    isSecret?: boolean;
  };
}

const levelBlueprints: LevelBlueprint[] = [
  {
    name: 'First spark',
    required: 0,
    reward: {
      type: GivebackRewardType.Other,
      title: '$10 to your causes',
      description:
        'On us, just for joining and picking the causes you care about.',
    },
  },
  {
    name: 'Newcomer',
    required: 25,
    reward: {
      type: GivebackRewardType.Cores,
      title: '25 Cores',
      description: 'A small boost for your first action.',
    },
  },
  {
    name: 'Helping hand',
    required: 50,
    reward: {
      type: GivebackRewardType.Cores,
      title: '50 Cores',
      description: 'A head start for showing up early.',
    },
  },
  {
    name: 'Regular',
    required: 100,
    reward: {
      type: GivebackRewardType.DailyPlus,
      title: '1 month of daily.dev Plus',
      description: 'A thank-you for moving the community forward.',
    },
  },
  {
    name: 'Contributor',
    required: 150,
    reward: {
      type: GivebackRewardType.Badge,
      title: 'Contributor badge',
      description: 'A mark of someone who keeps showing up.',
    },
  },
  {
    name: 'Supporter',
    required: 225,
    reward: { type: GivebackRewardType.Cores, title: '150 Cores' },
  },
  {
    name: 'Changemaker',
    required: 300,
    reward: {
      type: GivebackRewardType.Badge,
      title: 'Changemaker flair',
      isSecret: true,
    },
  },
  {
    name: 'Advocate',
    required: 400,
    reward: { type: GivebackRewardType.Cores, title: '300 Cores' },
  },
  {
    name: 'Trailblazer',
    required: 525,
    reward: {
      type: GivebackRewardType.DailyPlus,
      title: '3 months of Plus',
      isSecret: true,
    },
  },
  {
    name: 'Community pillar',
    required: 675,
    reward: {
      type: GivebackRewardType.Badge,
      title: 'Community pillar frame',
      isSecret: true,
    },
  },
  {
    name: 'Catalyst',
    required: 850,
    reward: { type: GivebackRewardType.Cores, title: '600 Cores' },
  },
  {
    name: 'Champion',
    required: 1050,
    reward: { type: GivebackRewardType.SwagCoupon, title: 'Sticker pack' },
  },
  {
    name: 'Luminary',
    required: 1300,
    reward: {
      type: GivebackRewardType.Badge,
      title: 'Luminary badge',
      isSecret: true,
    },
  },
  {
    name: 'Patron',
    required: 1600,
    reward: {
      type: GivebackRewardType.DailyPlus,
      title: '6 months of Plus',
      isSecret: true,
    },
  },
  {
    name: 'Vanguard',
    required: 1950,
    reward: {
      type: GivebackRewardType.Cores,
      title: '1,200 Cores',
      isSecret: true,
    },
  },
  {
    name: 'Headliner',
    required: 2350,
    reward: { type: GivebackRewardType.SwagCoupon, title: 'T-shirt coupon' },
  },
  {
    name: 'Mentor',
    required: 2800,
    reward: {
      type: GivebackRewardType.Badge,
      title: 'Mentor badge',
      isSecret: true,
    },
  },
  {
    name: 'Icon',
    required: 3350,
    reward: {
      type: GivebackRewardType.Badge,
      title: 'Icon profile frame',
      isSecret: true,
    },
  },
  {
    name: 'Mythic',
    required: 4000,
    reward: {
      type: GivebackRewardType.Other,
      title: 'Mystery drop',
      isSecret: true,
    },
  },
  {
    name: 'Legend',
    required: 5000,
    reward: {
      type: GivebackRewardType.SwagCoupon,
      title: 'Legend swag bundle',
      description: 'For the ones who go all in.',
      isSecret: true,
    },
  },
];

export const givebackLevels: GivebackLevel[] = levelBlueprints.map(
  (blueprint, index) => ({
    id: `level-${index + 1}`,
    levelNumber: index + 1,
    name: blueprint.name,
    requiredApprovedAmount: blueprint.required,
    reward: {
      id: `reward-${index + 1}`,
      type: blueprint.reward.type,
      title: blueprint.reward.title,
      secretTitle: 'Mystery reward',
      description: blueprint.reward.description,
      status:
        blueprint.required === 0
          ? GivebackRewardStatus.Unlocked
          : GivebackRewardStatus.Locked,
      isSecret: blueprint.reward.isSecret ?? false,
    },
  }),
);

export const givebackSponsors: GivebackSponsor[] = [
  {
    id: 'sponsor-vercel',
    name: 'Vercel',
    type: GivebackSponsorType.Company,
    amount: 5000,
    currency: GIVEBACK_CURRENCY,
    url: 'https://vercel.com',
    message: 'Backing the tools and people developers rely on.',
    isFounding: true,
    createdAt: '2026-05-20T09:00:00.000Z',
  },
  {
    id: 'sponsor-sentry',
    name: 'Sentry',
    type: GivebackSponsorType.Company,
    amount: 3000,
    currency: GIVEBACK_CURRENCY,
    url: 'https://sentry.io',
    message: 'Open source moves the world. Happy to chip in.',
    isFounding: true,
    createdAt: '2026-05-21T11:30:00.000Z',
  },
  {
    id: 'sponsor-supabase',
    name: 'Supabase',
    type: GivebackSponsorType.Company,
    amount: 2000,
    currency: GIVEBACK_CURRENCY,
    url: 'https://supabase.com',
    message: 'For the community that builds in public.',
    createdAt: '2026-05-23T14:10:00.000Z',
  },
  {
    id: 'sponsor-postman',
    name: 'Postman',
    type: GivebackSponsorType.Company,
    amount: 1500,
    currency: GIVEBACK_CURRENCY,
    url: 'https://postman.com',
    createdAt: '2026-05-24T08:45:00.000Z',
  },
  {
    id: 'sponsor-raycast',
    name: 'Raycast',
    type: GivebackSponsorType.Company,
    amount: 1000,
    currency: GIVEBACK_CURRENCY,
    url: 'https://raycast.com',
    createdAt: '2026-05-25T16:20:00.000Z',
  },
  {
    id: 'sponsor-ido',
    name: 'Ido Shamun',
    type: GivebackSponsorType.Individual,
    amount: 500,
    currency: GIVEBACK_CURRENCY,
    message: 'Proud to kick this off with the community.',
    isFounding: true,
    createdAt: '2026-05-19T07:00:00.000Z',
  },
  {
    id: 'sponsor-acme-studio',
    name: 'Northwind Labs',
    type: GivebackSponsorType.Company,
    amount: 750,
    currency: GIVEBACK_CURRENCY,
    createdAt: '2026-05-27T10:05:00.000Z',
  },
  {
    id: 'sponsor-maya',
    name: 'Maya Rodriguez',
    type: GivebackSponsorType.Individual,
    amount: 250,
    currency: GIVEBACK_CURRENCY,
    message: 'Giving back to the tools that taught me to code.',
    createdAt: '2026-05-28T19:40:00.000Z',
  },
  {
    id: 'sponsor-jonas',
    name: 'Jonas Keller',
    type: GivebackSponsorType.Individual,
    amount: 100,
    currency: GIVEBACK_CURRENCY,
    createdAt: '2026-05-29T12:15:00.000Z',
  },
  {
    id: 'sponsor-priya',
    name: 'Priya Nair',
    type: GivebackSponsorType.Individual,
    amount: 50,
    currency: GIVEBACK_CURRENCY,
    message: 'Every bit counts.',
    createdAt: '2026-05-30T15:55:00.000Z',
  },
];

const givebackSponsoredTotal = givebackSponsors.reduce(
  (sum, sponsor) => sum + sponsor.amount,
  0,
);

export const createMockCampaign = (
  overrides: Partial<GivebackCampaign> = {},
): GivebackCampaign => ({
  id: 'campaign-2026',
  name: 'Giveback',
  slug: 'giveback',
  status: GivebackCampaignStatus.Active,
  goalAmount: 10000,
  currency: GIVEBACK_CURRENCY,
  approvedAmount: 5000,
  pendingAmount: 450,
  sponsoredAmount: givebackSponsoredTotal,
  backersCount: 12480,
  backersLast24h: 214,
  stretchGoals: [
    {
      id: 'stretch-2500',
      amount: 2500,
      title: 'First grants sent',
      description: 'Initial donations reach Code.org and the EFF.',
    },
    {
      id: 'stretch-5000',
      amount: 5000,
      title: 'Open-source fund',
      description: 'A maintainer fund for the tools developers rely on.',
    },
    {
      id: 'stretch-7500',
      amount: 7500,
      title: 'Scholarships unlocked',
      description: 'Coding scholarships for underrepresented developers.',
    },
    {
      id: 'stretch-10000',
      amount: 10000,
      title: 'Full goal funded',
      description: 'All four community causes fully funded.',
    },
    {
      id: 'stretch-15000',
      amount: 15000,
      title: 'Stretch: we double it',
      description: 'daily.dev matches the next $5k, dollar for dollar.',
    },
  ],
  sponsors: givebackSponsors,
  heroCopy: 'Daily Dev funds the donation. You help unlock it.',
  ...overrides,
});

export const createMockUserProfile = (
  overrides: Partial<GivebackUserProfile> = {},
): GivebackUserProfile => ({
  currentLevel: 3,
  approvedContributionAmount: 85,
  pendingContributionAmount: 25,
  actionsCompletedCount: 4,
  selectedCauseIds: ['cause-code-org'],
  ...overrides,
});
