import type { ArticleChatter } from './types';
import { ChatterPlatform } from './types';

// POC: real captured dataset for "Better Models: Worse Tools" (Armin Ronacher),
// generated by the community-pulse POC pipeline (exact/topic-matched only, no
// fallback). Reddit was excluded from the POC by decision. Replace this with a
// live query keyed off the post's permalink / yggdrasilId when the data source
// is ready.
export const getMockChatter = (): ArticleChatter => ({
  pulse: {
    verdict:
      'Everyone agrees the bug is real — the fight is whether the fix breaks tool portability.',
    stance: 'divided',
    controversyLevel: 'lively',
    totalVoices: 620,
    momentum: 'rising',
    overallSplit: { agree: 58, mixed: 30, disagree: 12 },
    perPlatform: [
      {
        platform: ChatterPlatform.HackerNews,
        read: 'Trading harness war-stories',
        split: { agree: 60, mixed: 28, disagree: 12 },
      },
      {
        platform: ChatterPlatform.X,
        read: 'Sees vendor lock-in risk',
        split: { agree: 55, mixed: 33, disagree: 12 },
      },
    ],
    consensus: [
      'The core observation is real: strong models emit correct code edits but hallucinate non-existent tool params (e.g. requireUnique), failing strict harnesses.',
      'Lenient harnesses that auto-fix/retry train models into “good enough” habits that break in stricter tools.',
      'Minimal, well-chosen tool schemas beat complex ones in practice.',
    ],
    contention: [
      'Per-model harness tuning vs. portability',
      'Model regression or harness design fault?',
      'Vendor lock-in — can third-party agent tools survive?',
      'Determinism built on non-determinism',
    ],
    bottomLine:
      'A widely-praised diagnosis from Armin Ronacher: models are quietly being “trained off” by lenient harnesses. Nobody disputes the effect — the open question is whether the fix is per-model tuning (and the vendor lock-in that implies) or keeping tool schemas portable.',
    counterpoint: {
      text: 'The problem with hyper-targeting harnesses to models is you lock yourself into special model behaviors and make your sessions non-transferable.',
      attribution:
        'the_mitsuhiko (the author himself), cautioning against the obvious fix, on Hacker News',
    },
  },
  sources: [
    {
      platform: ChatterPlatform.HackerNews,
      heading: 'Hacker News · front page',
      subtitle: 'exact URL match · 226 points',
      stats: [
        { label: 'points', value: '226' },
        { label: 'comments', value: '81' },
      ],
      mood: 'HN is trading harness war-stories.',
      moodTone: 'split',
      summary:
        'Practitioners broadly praise the piece and pile on their own experiences — models botching unified-diff patches, minimal Sam-editor-syntax tools working great in ~650 tokens. The live debate: should harnesses ship per-model system prompts, or does that lock you into non-transferable, model-specific behavior?',
      sourceUrl: 'https://news.ycombinator.com/item?id=48788599',
      sourceLabel: 'Open discussion on Hacker News',
      defaultOpen: true,
      comments: [
        {
          id: 'hn1',
          author: 'dofm',
          avatar: '#ff6600',
          timeAgo: 'recent',
          text: 'As critical as I am about articles endlessly concerned with the weaknesses of closed cloud LLMs, this one is pretty great.',
        },
        {
          id: 'hn2',
          author: 'mappu',
          avatar: '#ff8a3d',
          timeAgo: 'recent',
          text: 'In my harness I implemented apply_patch taking unified diffs for patch -p1. I was shocked how bad models are at generating them.',
        },
        {
          id: 'hn3',
          author: 'the_mitsuhiko',
          avatar: '#9a5a2a',
          timeAgo: 'recent',
          text: 'The problem with hyper-targeting harnesses to models is that you end up locking yourself quickly into special model behaviors and make your sessions non-transferable.',
        },
      ],
    },
    {
      platform: ChatterPlatform.X,
      heading: 'X · developer amplification',
      subtitle: 'author reach + AI newsletters',
      stats: [
        { label: 'sentiment', value: '55% pos' },
        { label: 'framing', value: 'strategic' },
      ],
      mood: 'X is worried about vendor lock-in.',
      moodTone: 'mixed',
      summary:
        'X reframes the piece strategically: a detailed thread argues models get “trained off” by lenient vendor harnesses, so the real risk is training adaptation to a few big vendors’ ecosystems rather than general tool-use — which would make third-party agent tools progressively harder to build. AI newsletters amplify the takeaway.',
      sourceUrl: 'https://x.com/search?q=Better%20Models%20Worse%20Tools',
      sourceLabel: 'See posts on X',
      comments: [
        {
          id: 'x1',
          author: 'Xudong Han',
          handle: '@Xudong07452910',
          avatar: 'linear-gradient(135deg,#1d9bf0,#0f6fb8)',
          timeAgo: 'recent',
          text: 'The stronger the model, the more easily the tool leads it astray. If models keep training in lenient harnesses that auto-fix mistakes, they learn a dangerous habit: “good enough” — which becomes an error in stricter tools.',
        },
        {
          id: 'x2',
          author: 'zettersten',
          handle: '@zettersten',
          avatar: 'linear-gradient(135deg,#8b5cf6,#6d28d9)',
          timeAgo: 'recent',
          text: 'Better Models: Worse Tools — Armin Ronacher’s Thoughts and Writings',
        },
      ],
    },
  ],
});
