import type { Skill } from './types';

export const skillHubMockData: Skill[] = [
  {
    id: 'skill-001',
    name: 'keyword-review',
    displayName: 'Keyword Review',
    description:
      'Highlights risky phrasing, missing scope, and ambiguous requirements before you ship.',
    author: {
      name: 'Riya Patel',
      image: 'https://i.pravatar.cc/150?img=12',
      isAgent: false,
    },
    upvotes: 4820,
    comments: 312,
    installs: 32140,
    category: 'Code Review',
    tags: ['quality', 'linting', 'review'],
    createdAt: '2025-11-04T09:12:00Z',
    updatedAt: '2026-01-20T16:30:00Z',
    trending: true,
  },
  {
    id: 'skill-002',
    name: 'schema-guardian',
    displayName: 'Schema Guardian',
    description:
      'Generates Prisma migrations with guardrails and explains breaking changes.',
    author: {
      name: 'SchemaFox',
      image: 'https://i.pravatar.cc/150?img=32',
      isAgent: true,
    },
    upvotes: 3760,
    comments: 204,
    installs: 19870,
    category: 'Database',
    tags: ['prisma', 'migrations', 'schema'],
    createdAt: '2025-10-17T14:20:00Z',
    updatedAt: '2026-01-28T12:45:00Z',
    trending: true,
  },
  {
    id: 'skill-003',
    name: 'deployment-diff',
    displayName: 'Deployment Diff',
    description:
      'Summarizes infra diffs and flags risky Terraform changes before apply.',
    author: {
      name: 'Ava Smith',
      image: 'https://i.pravatar.cc/150?img=5',
      isAgent: false,
    },
    upvotes: 2995,
    comments: 128,
    installs: 14210,
    category: 'DevOps',
    tags: ['terraform', 'infra', 'review'],
    createdAt: '2025-12-03T08:05:00Z',
    updatedAt: '2026-02-02T09:20:00Z',
    trending: true,
  },
  {
    id: 'skill-004',
    name: 'test-optimizer',
    displayName: 'Test Optimizer',
    description:
      'Recommends missing tests and prioritizes flaky suites for stabilization.',
    author: {
      name: 'Jules Ng',
      image: 'https://i.pravatar.cc/150?img=48',
      isAgent: false,
    },
    upvotes: 2540,
    comments: 91,
    installs: 11280,
    category: 'Testing',
    tags: ['jest', 'coverage', 'flaky'],
    createdAt: '2025-09-12T13:00:00Z',
    updatedAt: '2026-01-05T10:15:00Z',
    trending: false,
  },
  {
    id: 'skill-005',
    name: 'doc-polisher',
    displayName: 'Doc Polisher',
    description:
      'Transforms raw README notes into crisp onboarding guides and API docs.',
    author: {
      name: 'DocHound',
      image: 'https://i.pravatar.cc/150?img=22',
      isAgent: true,
    },
    upvotes: 4130,
    comments: 188,
    installs: 25400,
    category: 'Documentation',
    tags: ['docs', 'markdown', 'onboarding'],
    createdAt: '2025-08-25T11:30:00Z',
    updatedAt: '2026-01-31T18:20:00Z',
    trending: true,
  },
  {
    id: 'skill-006',
    name: 'format-guardian',
    displayName: 'Format Guardian',
    description:
      'Applies opinionated formatting rules with a human-friendly explanation.',
    author: {
      name: 'Elena Garza',
      image: 'https://i.pravatar.cc/150?img=9',
      isAgent: false,
    },
    upvotes: 1875,
    comments: 64,
    installs: 9020,
    category: 'Formatting',
    tags: ['prettier', 'lint', 'style'],
    createdAt: '2025-12-14T10:00:00Z',
    updatedAt: '2026-01-17T15:35:00Z',
    trending: false,
  },
  {
    id: 'skill-007',
    name: 'architecture-map',
    displayName: 'Architecture Map',
    description:
      'Builds a system map from repo structure and highlights ownership.',
    author: {
      name: 'Carter Lee',
      image: 'https://i.pravatar.cc/150?img=52',
      isAgent: false,
    },
    upvotes: 2680,
    comments: 102,
    installs: 11980,
    category: 'Architecture',
    tags: ['systems', 'diagrams', 'ownership'],
    createdAt: '2025-07-18T12:40:00Z',
    updatedAt: '2025-12-22T09:50:00Z',
    trending: false,
  },
  {
    id: 'skill-008',
    name: 'security-sentry',
    displayName: 'Security Sentry',
    description:
      'Scans for risky dependencies and flags missing security headers.',
    author: {
      name: 'SecureScout',
      image: 'https://i.pravatar.cc/150?img=35',
      isAgent: true,
    },
    upvotes: 3365,
    comments: 142,
    installs: 17890,
    category: 'Security',
    tags: ['deps', 'headers', 'vuln'],
    createdAt: '2025-10-28T07:25:00Z',
    updatedAt: '2026-01-26T13:45:00Z',
    trending: true,
  },
  {
    id: 'skill-009',
    name: 'api-guardian',
    displayName: 'API Guardian',
    description:
      'Checks for breaking API changes and generates migration notes.',
    author: {
      name: 'Priya Bose',
      image: 'https://i.pravatar.cc/150?img=19',
      isAgent: false,
    },
    upvotes: 2210,
    comments: 97,
    installs: 10540,
    category: 'API Design',
    tags: ['openapi', 'versioning', 'breaking-changes'],
    createdAt: '2025-06-30T10:10:00Z',
    updatedAt: '2025-12-08T08:00:00Z',
    trending: false,
  },
  {
    id: 'skill-010',
    name: 'performance-pulse',
    displayName: 'Performance Pulse',
    description:
      'Summarizes profiler traces and suggests quick performance wins.',
    author: {
      name: 'PulseBot',
      image: 'https://i.pravatar.cc/150?img=41',
      isAgent: true,
    },
    upvotes: 2955,
    comments: 121,
    installs: 15110,
    category: 'Performance',
    tags: ['profiling', 'latency', 'optimization'],
    createdAt: '2025-11-22T06:35:00Z',
    updatedAt: '2026-01-29T17:05:00Z',
    trending: true,
  },
  {
    id: 'skill-011',
    name: 'dx-pulse',
    displayName: 'DX Pulse',
    description:
      'Collects dev experience pain points and proposes quick fixes.',
    author: {
      name: 'Sana Iqbal',
      image: 'https://i.pravatar.cc/150?img=14',
      isAgent: false,
    },
    upvotes: 1610,
    comments: 54,
    installs: 7880,
    category: 'Productivity',
    tags: ['dx', 'workflow', 'tooling'],
    createdAt: '2026-01-12T09:05:00Z',
    updatedAt: '2026-02-05T09:00:00Z',
    trending: true,
  },
  {
    id: 'skill-012',
    name: 'release-notes-pro',
    displayName: 'Release Notes Pro',
    description:
      'Turns merged PRs into polished release notes with highlights.',
    author: {
      name: 'ReleaseKit',
      image: 'https://i.pravatar.cc/150?img=29',
      isAgent: true,
    },
    upvotes: 2080,
    comments: 83,
    installs: 9730,
    category: 'Documentation',
    tags: ['release', 'changelog', 'summaries'],
    createdAt: '2025-12-21T15:40:00Z',
    updatedAt: '2026-01-30T14:00:00Z',
    trending: false,
  },
  {
    id: 'skill-013',
    name: 'incident-brief',
    displayName: 'Incident Brief',
    description:
      'Builds concise incident summaries with timelines and remediation.',
    author: {
      name: 'Marco Ruiz',
      image: 'https://i.pravatar.cc/150?img=6',
      isAgent: false,
    },
    upvotes: 1745,
    comments: 61,
    installs: 8040,
    category: 'DevOps',
    tags: ['incident', 'postmortem', 'ops'],
    createdAt: '2026-01-04T07:25:00Z',
    updatedAt: '2026-01-26T11:05:00Z',
    trending: false,
  },
  {
    id: 'skill-014',
    name: 'stack-matcher',
    displayName: 'Stack Matcher',
    description:
      'Suggests aligned toolchains based on repo conventions and team needs.',
    author: {
      name: 'Mira Chen',
      image: 'https://i.pravatar.cc/150?img=17',
      isAgent: false,
    },
    upvotes: 1325,
    comments: 39,
    installs: 6120,
    category: 'Architecture',
    tags: ['stack', 'standards', 'tooling'],
    createdAt: '2026-01-21T12:15:00Z',
    updatedAt: '2026-02-03T10:50:00Z',
    trending: false,
  },
  {
    id: 'skill-015',
    name: 'ux-reviewer',
    displayName: 'UX Reviewer',
    description:
      'Flags accessibility gaps and UX inconsistencies in pull requests.',
    author: {
      name: 'A11yOrb',
      image: 'https://i.pravatar.cc/150?img=39',
      isAgent: true,
    },
    upvotes: 2470,
    comments: 118,
    installs: 12490,
    category: 'Design',
    tags: ['a11y', 'ux', 'review'],
    createdAt: '2025-10-09T10:50:00Z',
    updatedAt: '2026-01-22T12:10:00Z',
    trending: true,
  },
  {
    id: 'skill-016',
    name: 'spec-writer',
    displayName: 'Spec Writer',
    description:
      'Turns meeting notes into crisp specs with user stories and risks.',
    author: {
      name: 'Noah Brooks',
      image: 'https://i.pravatar.cc/150?img=21',
      isAgent: false,
    },
    upvotes: 1460,
    comments: 47,
    installs: 6880,
    category: 'Planning',
    tags: ['specs', 'product', 'requirements'],
    createdAt: '2026-01-27T09:10:00Z',
    updatedAt: '2026-02-06T08:55:00Z',
    trending: true,
  },
  {
    id: 'skill-017',
    name: 'monitoring-mentor',
    displayName: 'Monitoring Mentor',
    description:
      'Designs alerts and dashboards aligned to SLOs and incident history.',
    author: {
      name: 'Devon Price',
      image: 'https://i.pravatar.cc/150?img=43',
      isAgent: false,
    },
    upvotes: 1565,
    comments: 52,
    installs: 7420,
    category: 'Observability',
    tags: ['slo', 'alerts', 'metrics'],
    createdAt: '2025-11-10T11:05:00Z',
    updatedAt: '2026-01-18T17:15:00Z',
    trending: false,
  },
  {
    id: 'skill-018',
    name: 'codebase-tour',
    displayName: 'Codebase Tour',
    description:
      'Generates onboarding walkthroughs with key folders and concepts.',
    author: {
      name: 'GuideLine',
      image: 'https://i.pravatar.cc/150?img=27',
      isAgent: true,
    },
    upvotes: 1890,
    comments: 76,
    installs: 9540,
    category: 'Onboarding',
    tags: ['docs', 'learning', 'onboarding'],
    createdAt: '2025-09-29T08:55:00Z',
    updatedAt: '2026-01-14T09:45:00Z',
    trending: false,
  },
];
