module.exports = {
  parser: '@typescript-eslint/parser',
  extends: [
    'airbnb',
    'airbnb-typescript',
    'plugin:testing-library/react',
    'plugin:jest-dom/recommended',
    'plugin:react/recommended',
    'plugin:@typescript-eslint/recommended',
    'prettier',
    'plugin:prettier/recommended',
    'plugin:react-hooks/recommended',
  ],
  plugins: ['prettier', 'tailwindcss', 'react-hooks', 'unused-imports'],
  parserOptions: {
    project: './tsconfig.eslint.json',
    ecmaVersion: 2020,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  settings: {
    react: {
      version: 'detect',
    },
    tailwindcss: {
      callees: ["classnames", "clsx", "ctl", "classNames"],
      officialSorting: true,
    }
  },
  env: {
    node: true,
  },
  rules: {
    'unused-imports/no-unused-imports': 'error',
    curly: ['error', 'all'],
    'import/no-cycle': ['error', {ignoreExternal: false, maxDepth: 3}],
    'no-restricted-exports': 'off',
    'react/prop-types': 0,
    'react/require-default-props': 0,
    'react/no-unused-prop-types': 0,
    'react/jsx-no-target-blank': 0,
    'react/function-component-definition': 'off',
    'react/jsx-no-constructed-context-values': 'off',
    'react/jsx-no-useless-fragment': 'off',
    'react/no-invalid-html-attribute': 'off',
    'react/no-unstable-nested-components': 'off',
    'import/prefer-default-export': 0,
    'import/no-import-module-exports': 'off',
    'import/no-relative-packages': 'off',
    'react/jsx-props-no-spreading': 0,
    'jsx-a11y/anchor-is-valid': 0,
    'react/no-danger': 0,
    '@typescript-eslint/return-await': 0,
    '@typescript-eslint/default-param-last': 'off',
    '@typescript-eslint/ban-ts-comment': [
      'error',
      {
        'ts-ignore': true,
        'ts-nocheck': true,
        'ts-check': false,
        'ts-expect-error': 'allow-with-description',
        minimumDescriptionLength: 5,
      },
    ],
    '@typescript-eslint/consistent-type-imports': 'error',
    '@typescript-eslint/no-duplicate-enum-values': 'off',
    '@typescript-eslint/no-unnecessary-type-constraint': 'off',
    'tailwindcss/classnames-order': 'warn',
    'tailwindcss/no-contradicting-classname': 'error',
    'no-promise-executor-return': 'off',
    'no-unsafe-optional-chaining': 'off',
    'prefer-regex-literals': 'off',
    'testing-library/await-async-events': 'off',
    'testing-library/no-node-access': 'off',
    'testing-library/no-unnecessary-act': 'off',
    'testing-library/no-wait-for-multiple-assertions': 'off',
    'testing-library/prefer-find-by': 'off',
    'testing-library/prefer-presence-queries': 'off',
    'jest-dom/prefer-checked': 'off',
    'jest-dom/prefer-enabled-disabled': 'off',
    'no-restricted-globals': [
      'error',
      {
        'name': 'isFinite',
        'message': 'Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite'
      },
      {
        'name': 'isNaN',
        'message': 'Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan'
      },
      'addEventListener',
      'blur',
      'close',
      'closed',
      'confirm',
      'defaultStatus',
      'defaultstatus',
      'event',
      'external',
      'find',
      'focus',
      'frameElement',
      'frames',
      'history',
      'innerHeight',
      'innerWidth',
      'length',
      'location',
      'locationbar',
      'menubar',
      'moveBy',
      'moveTo',
      'name',
      'onblur',
      'onerror',
      'onfocus',
      'onload',
      'onresize',
      'onunload',
      'open',
      'opener',
      'opera',
      'origin',
      'outerHeight',
      'outerWidth',
      'pageXOffset',
      'pageYOffset',
      'parent',
      'print',
      'removeEventListener',
      'resizeBy',
      'resizeTo',
      'screen',
      'screenLeft',
      'screenTop',
      'screenX',
      'screenY',
      'scroll',
      'scrollbars',
      'scrollBy',
      'scrollTo',
      'scrollX',
      'scrollY',
      'self',
      'status',
      'statusbar',
      'stop',
      'toolbar',
      'top',
    ],
    'no-restricted-imports': [
      'error',
      {
        paths: [
          {
            name: 'date-fns',
            importNames: ['isWeekend'],
            message: 'Please import from src/common instead.',
          },
          {
            name: 'next/link',
            message: 'Please import from src/common instead.',
          },
          {
            name: 'react-router-dom',
            importNames: ['Link'],
            message: 'Please import from src/common instead.',
          },
        ],
      },
    ],
    '@typescript-eslint/explicit-module-boundary-types': "off",
  },
};
