on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}
        run: |
          echo "Deployment successful"
          echo $CLIENT_PAYLOAD
